import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext.jsx';

export default function Register() {
  const { register } = useAuth();
  const navigate = useNavigate();
  const [form, setForm] = useState({ name: '', email: '', password: '', role: 'viewer' });
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e) { e.preventDefault(); setError(''); setBusy(true); try { await register(form); navigate('/'); } catch (err) { setError(err.response?.data?.message || 'Unable to create account'); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-slate-100 grid place-items-center px-4"><section className="w-full max-w-md rounded-2xl border bg-white p-8 shadow-sm"><div className="mb-8"><div className="mb-3 inline-flex rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">SIP</div><h1 className="text-2xl font-bold">Create account</h1><p className="mt-1 text-sm text-slate-500">Join the Standards Intelligence Platform</p></div><form onSubmit={submit} className="space-y-4"><Field label="Full name" value={form.name} onChange={v => setForm({ ...form, name: v })} /><Field label="Email" type="email" value={form.email} onChange={v => setForm({ ...form, email: v })} /><Field label="Password" type="password" value={form.password} onChange={v => setForm({ ...form, password: v })} /><label className="block"><span className="mb-1 block text-sm font-medium">Role</span><select value={form.role} onChange={e => setForm({ ...form, role: e.target.value })} className="w-full rounded-lg border px-3 py-3"><option value="viewer">Viewer</option><option value="supplier">Supplier</option><option value="procurement_officer">Procurement Officer</option></select></label>{error && <div className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}<button disabled={busy} className="w-full rounded-lg bg-slate-900 py-3 font-medium text-white disabled:opacity-50">{busy ? 'Creating…' : 'Create account'}</button></form><p className="mt-6 text-center text-sm text-slate-500">Already registered? <Link className="font-semibold text-slate-900" to="/login">Sign in</Link></p></section></main>;
}
function Field({ label, type = 'text', value, onChange }) { return <label className="block"><span className="mb-1 block text-sm font-medium">{label}</span><input required type={type} value={value} onChange={e => onChange(e.target.value)} className="w-full rounded-lg border px-3 py-3 outline-none focus:ring-2 focus:ring-slate-300" /></label>; }
