import { useEffect, useState } from 'react';
import api from '../services/api.js';
import { useAuth } from '../context/AuthContext.jsx';

const statusLabel={validated:'Validated',needs_review:'Needs review',high_risk:'High risk',failed:'Failed'};
const matchBasisLabel={
 'explicit-reference':'Explicit tender reference',
 'registry-keyword-match':'Registry keyword match',
 'vector-search':'Semantic / vector match'
};
const requirementStatusLabel={matched:'Strongly mapped',partially_matched:'Partially mapped',missing:'Standards gap',outdated_reference:'Outdated reference',review:'Review'};
export default function TenderValidation(){
 const {user}=useAuth(); const canValidate=['admin','procurement_officer'].includes(user?.role);
 const [documents,setDocuments]=useState([]),[tenders,setTenders]=useState([]),[documentId,setDocumentId]=useState(''),[title,setTitle]=useState(''),[text,setText]=useState(''),[result,setResult]=useState(null),[selectedTender,setSelectedTender]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function load(){setLoading(true);try{const [d,t]=await Promise.all([api.get('/documents?limit=50&documentType=tender&status=processed'),api.get('/tenders')]);setDocuments(d.data.data.items||[]);setTenders(t.data.data.items||[]);}catch(e){setError(e.response?.data?.message||'Unable to load tender validation data')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function validate(){if(!documentId&&!text.trim())return;setBusy(true);setError('');setResult(null);try{const r=await api.post('/tenders/validate',{documentId:documentId||undefined,title:title.trim()||undefined,text:documentId?undefined:text},{timeout:120000});setResult(r.data.data);await load()}catch(e){setError(e.response?.data?.message||e.code==='ECONNABORTED'?'Tender validation timed out. Check the backend logs and try again.':'Tender validation failed')}finally{setBusy(false)}}
 async function openTender(id){try{const r=await api.get(`/tenders/${id}`);setSelectedTender(r.data.data);setResult(null)}catch(e){setError(e.response?.data?.message||'Unable to open tender report')}}
 const report=result?.report||selectedTender?.report; const requirements=result?.requirements||selectedTender?.requirements||[]; const status=result?.tender?.validationStatus||selectedTender?.validationStatus;
 return <div className="tender-page">
  <div className="tender-header"><div><h1>Tender Validation</h1><p>Check whether requirements written in a tender can be mapped to verified Indian Standards in the Standards Registry.</p></div><span className="tender-policy">Standards coverage · decision support</span></div>
  <section className="tender-panel tender-explainer"><div className="tender-explainer-icon">✓</div><div><h2>What this page validates</h2><p>This workflow validates <strong>standards coverage of a tender</strong> — not whether a supplier has actually complied. It extracts tender requirements, finds the strongest available Standard Registry matches, checks their registry status/verification, and highlights coverage gaps for review.</p><div className="tender-flow"><span>Tender</span><b>→</b><span>Requirements</span><b>→</b><span>Standards Registry</span><b>→</b><span>Mapping</span><b>→</b><span>Coverage &amp; Risk</span></div><p className="tender-note"><strong>Stage 2:</strong> Supplier compliance is a separate workflow requiring bidder evidence such as technical datasheets, certificates and test reports.</p></div></section>
  {canValidate&&<section className="tender-panel"><div className="tender-panel-title"><div><h2>Validate a tender</h2><p>Use a processed document classified as <strong>Tender</strong> or paste tender requirements directly. Standards, resumes, CVs and other non-tender documents are not accepted for tender validation.</p></div></div><div className="tender-form-grid"><div className="tender-field"><label>Processed tender document</label><select value={documentId} onChange={e=>{setDocumentId(e.target.value);if(e.target.value)setText('')}}><option value="">Select a document</option>{documents.filter(d=>d.status==='processed').map(d=><option key={d._id} value={d._id}>{d.originalName} · {d.chunkCount||0} chunks</option>)}</select></div><div className="tender-field"><label>Report title</label><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Pharmaceutical procurement tender"/></div></div><div className="tender-or"><span>OR</span></div><div className="tender-field"><label>Paste tender text</label><textarea value={text} disabled={Boolean(documentId)} onChange={e=>setText(e.target.value)} placeholder="Paste tender requirements here if you are not using an uploaded document..."/></div><div className="tender-actions"><button onClick={validate} disabled={busy||(!documentId&&!text.trim())}>{busy?'Validating…':'Validate Tender'}</button></div></section>}
  {error&&<div className="tender-error">{error}</div>}
  {report&&<section className="tender-panel tender-report"><div className="tender-report-header"><div><h2>Validation report</h2><p>{result?.tender?.title||selectedTender?.title}</p></div><span className={`tender-status ${status}`}>{statusLabel[status]||status}</span></div><div className="tender-report-intro"><strong>Interpretation:</strong> This report measures how well the tender's requirements are covered by standards available in the registry. A gap means the engine could not establish sufficient standards coverage; it does not mean a bidder is non-compliant.</div><div className="tender-metrics"><div><span>Requirements</span><strong>{report.requirementsAnalyzed??0}</strong></div><div><span>Strongly mapped</span><strong>{report.matchedRequirements??0}</strong></div><div><span>Standards gaps</span><strong>{report.missingRequirements??0}</strong></div><div><span>Standards coverage</span><strong>{Math.round((report.coverage||0)*100)}%</strong></div><div><span>Review flags</span><strong>{report.riskSummary?.totalFlags??0}</strong></div></div><div className="tender-report-grid"><div><h3>Standards coverage gaps</h3>{(report.standardsCoverageGaps||report.complianceGaps)?.length?(report.standardsCoverageGaps||report.complianceGaps).map((g,i)=><div className="tender-gap" key={i}>{g.text}</div>):<p className="tender-muted">No standards coverage gaps detected from the available registry data.</p>}<p className="tender-note">These are registry coverage gaps, not supplier compliance failures.</p></div><div><h3>Standards explicitly referenced by the tender</h3>{report.explicitStandards?.length?<div className="tender-tags">{report.explicitStandards.map(x=><span key={x}>{x}</span>)}</div>:<p className="tender-muted">No explicit IS/ISO/IEC references detected.</p>}<p className="tender-note">An explicit reference means the tender text itself names the standard.</p></div></div></section>}
  {requirements.length>0&&<section className="tender-panel"><div className="tender-panel-title"><div><h2>Requirement-by-requirement validation</h2><p>Each requirement is mapped to the best available Standard Registry record. The status describes the strength of that mapping, not supplier compliance.</p></div></div><div className="requirement-list">{requirements.map((r,i)=><div className="requirement-card" key={r._id||i}><div className="requirement-card-top"><div><span className="requirement-index">R{i+1}</span><span className="requirement-type">{r.type}</span></div><div className="requirement-badges"><span className={`req-status ${r.status}`}>{requirementStatusLabel[r.status]||r.status.replaceAll('_',' ')}</span><span className={`risk-badge ${r.riskLevel}`}>{r.riskLevel} risk</span></div></div><p className="requirement-text">{r.text}</p>{r.evidence?.length?<div className="requirement-evidence"><strong>Best registry match</strong><span>{r.evidence[0].standardNumber||'Unnumbered registry record'} · {r.evidence[0].title}</span><small>Match score: {Math.round((r.evidence[0].score||0)*100)}% · {r.evidence[0].verified?'Verified metadata':'Unverified metadata'} · {matchBasisLabel[r.evidence[0].source]||'Registry evidence'}</small>{r.evidence[0].why && <p><strong>Why this match?</strong> {r.evidence[0].why}</p>}</div>:<div className="requirement-missing">No matching standard found in the current registry. This is a standards coverage gap, not a supplier compliance finding.</div>}</div>)}</div></section>}
  <section className="tender-panel"><div className="tender-panel-title"><div><h2>Previous validations</h2><p>Open a saved report to review its requirements.</p></div></div>{loading?<p className="tender-muted">Loading…</p>:!tenders.length?<p className="tender-muted">No tender validations yet.</p>:<div className="tender-history">{tenders.map(t=><button key={t._id} onClick={()=>openTender(t._id)} className="tender-history-item"><div><strong>{t.title}</strong><span>{new Date(t.createdAt).toLocaleString()}</span></div><span className={`tender-status ${t.validationStatus}`}>{statusLabel[t.validationStatus]||t.validationStatus}</span></button>)}</div>}</section>
 </div>
}
